/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Teclado_Teclado.h"
#include "Clock_1.h"
#include "isrTEC.h"
#include "LCD.h"
#include "Counter.h"
#include "Clock_2.h"
#include "isrCONT.h"
#include "PWM_1.h"
#include "isrTEC_1.h"
#include "Clock_3.h"
#include "Pin_1_aliases.h"
#include "Pin_1.h"
#include "Teclado_Status_Reg.h"
#include "Teclado_Rows_aliases.h"
#include "Teclado_Rows.h"
#include "Teclado_Columns_aliases.h"
#include "Teclado_Columns.h"
#include "LCD_LCDPort_aliases.h"
#include "LCD_LCDPort.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

